---
- name: Kubernetes Health Checks
  hosts: localhost
  gather_facts: false
  vars:
    # Set your Kubernetes API URL and token here
    api_url: "https://10.96.0.1:443"
    api_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlltTlZTTXpLeEpmTi0xekpwdUxUQUgyLTlPUW5kMWRVMFN1d0cxajBOU1kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM1MjE3Njc5LCJpYXQiOjE3MzUxMzEyNzksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYmM2YmI0ZDItZjNlYi00YTYyLWEzODEtYjdiMTNiOTkxOTZmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJmdXNpb24iLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZnVzaW9uIiwidWlkIjoiNDAyM2YzMzYtNjM4Mi00ZmYwLWI0YmQtZDJkNmY1ZGI3YWI1In19LCJuYmYiOjE3MzUxMzEyNzksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpmdXNpb246ZnVzaW9uIn0.MRM6Ocrixf-5U4jJieQ8oMzMcr78ssnyJS5cziXb5xLaSLlW8gUf54EqkpTViC7Vn604mDvDzDLlRZImVNJsFw-B7mY1ImQ6gxNlI-iVrpt-xX5uvOV1ZV1nKFP158bBnnO7T6csY4zJOYaUOCsvAM9KPujh6sKKnrBk4p8QJXnLGQzsps7gjZXnTNyBZmUZXs8nyWKBNLveYLxxGh9Y7MBHxbqTK80SUNbZDDuEbm3yXdlSslmseL5ysDW0-7J39rMW0qMXkhhqhNEYDCYe_p2P9IEdzm3sMBt9UUq9EEz6G7HO0dFy92sKJYDp4WunlHcHX23WED0RPHuwFtx70g"
    
  tasks:
    - name: Check Cluster Component Status
      uri:
        url: "{{ api_url }}/api/v1/nodes"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: no
      register: cluster_status
    - name: Display Cluster Component Status
      debug:
        msg: "{{ cluster_status.json }}"

    - name: Get Persistent Volume Claims Status
      uri:
        url: "{{ api_url }}/api/v1/persistentvolumeclaims"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: no
      register: pvc_status
    - name: Display Persistent Volume Claims Status
      debug:
        msg: "{{ pvc_status.json.items }}"

    - name: Get Persistent Volumes Status
      uri:
        url: "{{ api_url }}/api/v1/persistentvolumes"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: no
      register: pv_status
    - name: Display Persistent Volumes Status
      debug:
        msg: "{{ pv_status.json.items }}"

    - name: Get Monitoring Components (Prometheus, Metrics Server)
      uri:
        url: "{{ api_url }}/api/v1/namespaces/monitoring/pods"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: no
      register: monitoring_components
    - name: Display Monitoring Components
      debug:
        msg: "{{ monitoring_components.json.items }}"

    - name: Get Namespace Status
      uri:
        url: "{{ api_url }}/api/v1/namespaces"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: no
      register: namespace_status
    - name: Display Namespace Status
      debug:
        msg: "{{ namespace_status.json.items }}"
