---
- name: Check web status of multiple websites
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check the status of each website serially with retries
      uri:
        url: "{{ item }}"
        method: GET
        return_content: no
        status_code: 200
      register: result
      retries: 2
      delay: 5
      with_items:
        - http://google.com
        - http://facebook.com
        - http://twitter.com
        - http://youtube.com
        - http://amazon.com
        - http://microsoft.com
        - http://apple.com
        - http://github.com
        - http://wikipedia.org
        - http://reddit.com
        - http://stackoverflow.com
        - http://linkedin.com
        - http://bing.com
        - http://yahoo.com
        - http://example1.com
      ignore_errors: yes  # Ignore errors to continue checking other URLs

    - name: Process and store web status results
      set_fact:
        web_status_results: "{{ web_status_results | default([]) + [{'url': item.item, 'status': (item.status | ternary('Success', 'Failed')), 'code': item.status}] }}"
      loop: "{{ result.results }}"
      when: result is defined

    - name: Display the results of the web status check
      debug:
        msg: "URL={{ item.url }}, Status={{ item.status }}, Code={{ item.code }}"
      loop: "{{ web_status_results }}"

