---
- name: Test URL status
  hosts: localhost
  tasks:
    - name: Set url details
      set_fact:
        test_urls:
          - "https://google.com"
          - "https://yahoo.com"
          - "https://bing.com"
          - "https://github.com"
          - "https://twitter.com"
          - "https://facebook.com"
          - "https://amazon.com"
          - "https://wikipedia.org"
          - "https://reddit.com"
          - "https://linkedin.com"
          - "https://instagram.com"
          - "https://stackoverflow.com"
          - "https://apple.com"
          - "https://microsoft.com"
          - "https://python.org"
          - "https://youtube.com"
          - "https://wordpress.org"
          - "https://npmjs.com"
          - "https://gitlab.com"
          - "https://dev.to"
          - "https://example1.com"
          - "https://example2.com"

    - name: "Check the status of each URL from localhost"
      uri:
        url: "{{ item }}"
        method: GET
        timeout: 5  # Timeout set to 5 seconds
        return_content: yes
      register: out
      with_items: "{{ test_urls }}"
      ignore_errors: yes  # Continue even if the URL check fails
      failed_when: false  # Prevent the task from failing

    - name: Print the status of each URL
      debug:
        msg: "URL: {{ item }} - Status: {{ out.results[ansible_loop.index0].status | default('Failed') }}"
      with_items: "{{ test_urls }}"

