---
- name: Check website status
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check status of websites
      uri:
        url: "{{ item }}"
        return_content: no
        status_code: 200,301,302,404,500
      register: result
      with_items:
        - http://google.com
        - http://facebook.com
        - http://twitter.com
        - http://linkedin.com
        - http://github.com
        - http://stackoverflow.com
        - http://reddit.com
        - http://amazon.com
        - http://apple.com
        - http://microsoft.com
        - http://netflix.com
        - http://yahoo.com
        - http://bing.com
        - http://instagram.com
        - http://wikipedia.org
        - http://quora.com
        - http://pinterest.com
        - http://tumblr.com
        - http://ebay.com
        - http://paypal.com
        - http://example1.com
        - http://example2.com

    - name: Display website status
      debug:
        msg: "URL: {{ item.item }}, Code: {{ item.status }}, Status: {{ item.msg }}"
      with_items: "{{ result.results }}"
