---
- name: Check web status of multiple websites
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check the status of the websites in parallel
      uri:
        url: "{{ item }}"
        method: GET
        return_content: no
        status_code: 200
      register: result
      with_items:
        - http://example1.com
        - http://example2.com
        - http://example3.com
        - http://example4.com
        - http://example5.com
        - http://example6.com
        - http://example7.com
        - http://example8.com
        - http://example9.com
        - http://example10.com
        - http://example11.com
        - http://example12.com
        - http://example13.com
        - http://example14.com
        - http://example15.com
        - http://example16.com
        - http://example17.com
        - http://example18.com
        - http://example19.com
        - http://example20.com
      async: 60
      poll: 0

    - name: Wait for all web checks to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      with_items: "{{ result.results }}"
      until: job_result.finished
      retries: 5
      delay: 5

    - name: Display the results of the web status check
      debug:
        msg: "Web status for {{ item.item }}: {{ item.status }}"
      with_items: "{{ result.results }}"
      when: item.status == 200

