---
- name: Check web status of multiple websites
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check the status of the websites serially with retries
      uri:
        url: "{{ item }}"
        method: GET
        return_content: no
        status_code: 200
      register: result
      retries: 2
      delay: 3
      with_items:
        - http://google.com
        - http://facebook.com
        - http://twitter.com
        - http://youtube.com
        - http://amazon.com
        - http://microsoft.com
        - http://apple.com
        - http://github.com
        - http://wikipedia.org
        - http://reddit.com
        - http://stackoverflow.com
        - http://linkedin.com
        - http://bing.com
        - http://yahoo.com
        - http://example1.com

    - name: Display the results of the web status check
      debug:
        msg: "URL={{ item.item }}, Status={{ item.status | ternary('Success', 'Failed') }}, Code={{ item.status }}"
      with_items: "{{ result.results }}"

