---
- name: Check website status in parallel
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check status of websites in parallel
      uri:
        url: "{{ item }}"
        return_content: no
        status_code: 200
      register: result
      with_items:
        - https://google.com
        - https://facebook.com
        - https://twitter.com
        - https://linkedin.com
        - https://github.com
        - https://stackoverflow.com
        - https://reddit.com
        - https://amazon.com
        - https://apple.com
        - https://microsoft.com
        - https://netflix.com
        - https://yahoo.com
        - https://bing.com
        - https://instagram.com
        - https://wikipedia.org
        - https://quora.com
        - https://pinterest.com
        - https://tumblr.com
        - https://ebay.com
        - https://paypal.com
        - https://examplexxxx.com
        - https://exampleyyyy.com
      async: 45
      poll: 0
      ignore_errors: yes

    - name: Wait for all website checks to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 2
      delay: 5
      with_items: "{{ result.results }}"
      ignore_errors: yes

    - name: Display website statuses
      debug:
        msg: "URL={{ item.item.item }} Code={{ item.status }} Status={{ item.msg }}"
      with_items: "{{ job_result.results }}"

