---
- name: Check website status
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check status of websites
      uri:
        url: "{{ item }}"
        return_content: no
        status_code: 200
      register: result
      with_items:
        - https://google.com
        - https://facebook.com
        - https://twitter.com
        - https://linkedin.com
        - https://github.com
        - https://stackoverflow.com
        - https://reddit.com
        - https://amazon.com
        - https://apple.com
        - https://microsoft.com
        - https://netflix.com
        - https://yahoo.com
        - https://bing.com
        - https://instagram.com
        - https://wikipedia.org
        - https://quora.com
        - https://pinterest.com
        - https://tumblr.com
        - https://ebay.com
        - https://paypal.com
        - https://examplexxxx.com
        - https://exampleyyyy.com
      ignore_errors: yes

    - name: Display website status
      debug:
        url: "URL={{ item.item }}"
        code: "{{ item.status }}"
        description: "{ item.msg }}"
      with_items: "{{ result.results }}"
